spring:
  application:
    name: spring-ai
  ai: 
    openai:
      api-key: ${API_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com"
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash